config/routes.rb
Rails.application.routes.draw do
  resources :users

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


resources :active_users, only: [ :index ]
end

app/models/active_user.rb
class ActiveUser < ApplicationRecord
  enum status: { active: 0, inactive: 1 }
  def readonly?
    true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  enum status: { active: 0, inactive: 1 }

  validates :first_name, :last_name, :status, presence: true
end

app/controllers/active_users_controller.rb
require "csv"
require "prawn"

class ActiveUsersController < ApplicationController
  def index
    @active_users = ActiveUser.all

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv, filename: "active_users-#{Date.today}.csv" }
      format.xlsx { render xlsx: "index", filename: "active_users-#{Date.today}.xlsx" }
      format.pdf { send_data generate_pdf, filename: "active_users-#{Date.today}.pdf", type: "application/pdf" }
    end
  end

  private

  def generate_csv
    CSV.generate(headers: true) do |csv|
      csv << %w[First_Name Last_Name Status]
      @active_users.each do |user|
        csv << [user.first_name, user.last_name, user.status]
      end
    end
  end

  def generate_pdf
    Prawn::Document.new do |pdf|
      pdf.text "Active Users", size: 20, style: :bold
      pdf.move_down 10
      @active_users.each do |user|
        pdf.text "First Name: #{user.first_name}, Last Name: #{user.last_name}, Status: #{user.status}"
      end
    end.render
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :status)
    end
end

app/helpers/active_users_helper.rb
module ActiveUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_users/index.html.erb
<div class="flex flex-col w-full text-white">
  <div class="text-center text-2xl font-semibold mb-4 text-yellow-500">
    Active Users
  </div>
  <div class="flex flex-col w-full">
    <div class="w-full flex text-lg justify-start items-center mb-4">
      <div data-controller="dropdown" class="relative">
        <button
          data-action="click->dropdown#toggle click@window->dropdown#hide"
          class="bg-blue-500 text-yellow-500 border-[2px] border-yellow-500 px-4 py-2 rounded-lg"
        >
          Export
        </button>

        <div
          data-dropdown-target="menu"
          class="hidden absolute right-0 mt-2 bg-white border rounded-lg shadow-lg"
        >
          <div class="py-1">
            <%= link_to "XLSX", active_users_path(format: :xlsx), class: "block px-4 py-2 text-gray-700 hover:bg-gray-100" %>
            <%= link_to "PDF", active_users_path(format: :pdf), class: "block px-4 py-2 text-gray-700 hover:bg-gray-100" %>
            <%= link_to "CSV", active_users_path(format: :csv), class: "block px-4 py-2 text-gray-700 hover:bg-gray-100" %>
          </div>
        </div>
      </div>
    </div>
    <table class="table-auto border-collapse border border-gray-200 w-full">
      <thead>
        <tr class="bg-blue-500">
          <th class="border px-4 py-2">First Name</th>
          <th class="border px-4 py-2">Last Name</th>
          <th class="border px-4 py-2">Status</th>
        </tr>
      </thead>
      <tbody>
        <% @active_users.each do |user| %>
          <tr class="border hover:bg-yellow-500 hover:text-slate-800">
            <td class="border px-4 py-2"><%= user.first_name %></td>
            <td class="border px-4 py-2"><%= user.last_name %></td>
            <td class="border px-4 py-2"><%= user.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Training Ground" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-800">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">First name:</strong>
    <%= user.first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Last name:</strong>
    <%= user.last_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= user.status %>
  </p>

</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Show this user", @user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Users" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to "New user", new_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="users" class="min-w-full">
    <% @users.each do |user| %>
      <%= render user %>
      <p>
        <%= link_to "Show this user", user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to "Edit this user", edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this user", @user, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>